/**
 * lib/industryImages.ts
 *
 * Reads the industry image library manifest and returns image URLs
 * for a given industry slug and slot (hero, card1–card4).
 *
 * The manifest is generated by generate_image_library.py and should be
 * committed to the repo at public/image-library/manifest.json
 *
 * Usage:
 *   import { getIndustryImage, getIndustryImages } from '@/lib/industryImages'
 *
 *   const heroUrl  = getIndustryImage('plumbing', 'hero')
 *   const allUrls  = getIndustryImages('plumbing')
 *   // → { hero: '...', card1: '...', card2: '...', card3: '...', card4: '...' }
 */

export type ImageSlot = 'hero' | 'card1' | 'card2' | 'card3' | 'card4'

export interface IndustryImageSet {
  hero:  string
  card1: string
  card2: string
  card3: string
  card4: string
}

// Fallback gradient placeholders (used when an industry image isn't found)
const FALLBACK_GRADIENTS: Record<ImageSlot, string> = {
  hero:  'linear-gradient(135deg, #1e3a5f 0%, #2d6a9f 100%)',
  card1: 'linear-gradient(135deg, #2d4a7a 0%, #4a90d9 100%)',
  card2: 'linear-gradient(135deg, #1a3a5c 0%, #3a7abf 100%)',
  card3: 'linear-gradient(135deg, #243b55 0%, #141e30 100%)',
  card4: 'linear-gradient(135deg, #1e3c72 0%, #2a5298 100%)',
}

// Inline manifest — populated after running generate_image_library.py
// Replace this with: import manifest from '@/public/image-library/manifest.json'
// once the manifest file is committed to the repo.
let _manifest: Record<string, { label: string; images: Record<string, { url: string | null }> }> | null = null

function getManifest() {
  if (_manifest) return _manifest
  try {
    // In Next.js this works at build time and runtime
    // eslint-disable-next-line @typescript-eslint/no-var-requires
    _manifest = require('@/public/image-library/manifest.json')
  } catch {
    _manifest = {}
  }
  return _manifest!
}

/**
 * Get a single image URL for an industry + slot.
 * Returns the Supabase Storage URL or null if not found.
 */
export function getIndustryImage(industrySlug: string, slot: ImageSlot): string | null {
  const manifest = getManifest()
  const industry = manifest[industrySlug] ?? manifest['other']
  if (!industry) return null
  return industry.images[slot]?.url ?? null
}

/**
 * Get all 5 image URLs for an industry.
 * Falls back to 'other' industry images if the slug isn't found.
 * Returns null values for any slots that failed generation.
 */
export function getIndustryImages(industrySlug: string): Partial<IndustryImageSet> {
  const slots: ImageSlot[] = ['hero', 'card1', 'card2', 'card3', 'card4']
  return Object.fromEntries(
    slots.map(slot => [slot, getIndustryImage(industrySlug, slot)])
  ) as Partial<IndustryImageSet>
}

/**
 * Get an image URL with an inline CSS fallback.
 * Safe to use directly in style={{ backgroundImage: ... }}
 */
export function getIndustryImageWithFallback(
  industrySlug: string,
  slot: ImageSlot
): string {
  const url = getIndustryImage(industrySlug, slot)
  if (url) return `url(${url})`
  return FALLBACK_GRADIENTS[slot]
}

/**
 * Map display industry names to slugs (matches /preview wizard step 1)
 */
export const INDUSTRY_SLUG_MAP: Record<string, string> = {
  'Plumbing':          'plumbing',
  'HVAC':              'hvac',
  'Electrical':        'electrical',
  'Landscaping':       'landscaping',
  'Cleaning Services': 'cleaning',
  'Roofing':           'roofing',
  'Painting':          'painting',
  'Auto Repair':       'automotive',
  'Home Remodeling':   'remodeling',
  'Pest Control':      'pest_control',
  'Moving Services':   'moving',
  'Other':             'other',
}

export function industryLabelToSlug(label: string): string {
  return INDUSTRY_SLUG_MAP[label] ?? 'other'
}
