import { createAdminClient } from "@/lib/supabase-server";
import { NextResponse } from "next/server";
import Anthropic from "@anthropic-ai/sdk";

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
const STITCH_API_KEY = process.env.STITCH_API_KEY!;

async function stitchFetch(path: string, method = "GET", body?: object) {
  const res = await fetch(`https://stitch.googleapis.com/v1alpha${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${STITCH_API_KEY}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
    signal: AbortSignal.timeout(240000),
  });
  if (!res.ok) throw new Error(`Stitch ${method} ${path} → ${res.status}: ${await res.text()}`);
  return res.json();
}

export async function POST(request: Request) {
  const { business_id } = await request.json();
  if (!business_id)
    return NextResponse.json({ error: "business_id required" }, { status: 400 });

  const supabase = createAdminClient();
  const { data: business } = await supabase
    .from("businesses").select("*").eq("id", business_id).single();
  if (!business)
    return NextResponse.json({ error: "Business not found" }, { status: 404 });

  await supabase.from("generation_jobs")
    .update({ status: "running", started_at: new Date().toISOString() })
    .eq("business_id", business_id).eq("status", "pending");

  try {
    // ── Step 1: Claude generates content ──────────────────────────────────
    const aiRes = await anthropic.messages.create({
      model: "claude-haiku-4-5-20251001",
      max_tokens: 2000,
      messages: [{ role: "user", content: `Generate website content for this business as JSON only:
Business: ${business.name}
Description: ${business.description}
Location: ${business.city}, ${business.state}
Phone: ${business.phone || ""}

Return ONLY valid JSON:
{
  "tagline": "one-liner tagline",
  "services": [{"name":"","description":"","icon":"emoji"}],
  "stats": [{"value":"10+","label":"Years Experience"},{"value":"500+","label":"Happy Customers"},{"value":"100%","label":"Satisfaction"},{"value":"24/7","label":"Available"}],
  "testimonials": [{"name":"","text":"","rating":5,"location":""}],
  "meta_title": "under 60 chars",
  "meta_description": "under 160 chars",
  "keywords": ["kw1","kw2","kw3"],
  "accent_color": "#hexcolor",
  "emoji": "single emoji",
  "blog_titles": ["Title 1","Title 2","Title 3"],
  "social_posts": {"facebook":["p1","p2","p3"],"instagram":["p1 #tags","p2 #tags","p3 #tags"],"linkedin":["p1","p2","p3"]}
}` }],
    });

    const rawText = aiRes.content[0].type === "text" ? aiRes.content[0].text : "";
    const jsonMatch = rawText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) throw new Error("No JSON in Claude response");
    const generated = JSON.parse(jsonMatch[0]);

    // ── Step 2: Create Stitch project for this customer ───────────────────
    const projectTitle = `${business.name} — ${business.city}, ${business.state}`;
    const project = await stitchFetch("/projects", "POST", { title: projectTitle });
    const projectId = project.name.split("/")[1];
    console.log(`[generate] Stitch project created: ${projectId}`);

    // ── Step 3: Generate base homepage with real business data ────────────
    const basePrompt = `Homepage for ${business.name}. ${business.description}. Located in ${business.city}, ${business.state}. Phone: ${business.phone || ""}. Tagline: "${generated.tagline}". Services: ${generated.services.map((s: any) => s.name).join(", ")}. Professional small business website.`;

    const baseRes = await stitchFetch(`/projects/${projectId}/screens`, "POST", {
      prompt: basePrompt,
      model_id: "GEMINI_3_FLASH",
    });

    // Extract base screen ID
    const screens = baseRes.outputComponents?.flatMap((c: any) =>
      c.design?.screens || []
    ) || [];
    if (!screens.length) throw new Error("No screen generated by Stitch");
    const baseScreenId = screens[0].id;
    console.log(`[generate] Base screen: ${baseScreenId}`);

    // ── Step 4: Generate 2 more style variants ────────────────────────────
    const variantRes = await stitchFetch(`/projects/${projectId}/screens:generateVariants`, "POST", {
      selected_screen_ids: [baseScreenId],
      prompt: `Generate 2 more style variants for ${business.name} — same content, very different visual styles.`,
      variant_options: {
        variant_count: 2,
        creative_range: "REIMAGINE",
        aspects: ["COLOR_SCHEME", "LAYOUT", "TEXT_FONT"],
      },
    });

    const variantScreens = variantRes.outputComponents?.flatMap((c: any) =>
      c.design?.screens || []
    ) || [];
    console.log(`[generate] Variants generated: ${variantScreens.length}`);

    // Collect all 3 screen IDs + thumbnails
    const allScreens = [screens[0], ...variantScreens].slice(0, 3);
    const templateOptions = allScreens.map((s: any, i: number) => ({
      id: s.id,
      thumbnail: s.screenshot?.downloadUrl || "",
      label: ["Style A", "Style B", "Style C"][i],
    }));

    // ── Step 5: Save to Supabase ──────────────────────────────────────────
    await supabase.from("websites").upsert({
      business_id,
      status: "picking_template",
      services: generated.services,
      stats: generated.stats,
      testimonials: generated.testimonials,
      pages: ["Home", "Services", "About", "Contact"],
      meta_title: generated.meta_title,
      meta_description: generated.meta_description,
      schema_markup: {
        "@context": "https://schema.org",
        "@type": "LocalBusiness",
        name: business.name,
        description: business.description,
        telephone: business.phone,
        address: { "@type": "PostalAddress", addressLocality: business.city, addressRegion: business.state },
      },
      keywords: generated.keywords,
      stitch_project_id: projectId,
      stitch_screens: templateOptions,
    }, { onConflict: "business_id" });

    await supabase.from("businesses").update({
      tagline: generated.tagline,
      accent_color: generated.accent_color,
      emoji: generated.emoji,
    }).eq("id", business_id);

    // Blog + social posts
    await supabase.from("blog_posts").insert(
      generated.blog_titles.map((title: string) => ({
        business_id, title, status: "draft",
        excerpt: `Expert insights from ${business.name}.`,
        word_count: 800, seo_score: Math.floor(Math.random() * 15) + 82,
      }))
    );
    const socialPosts: any[] = [];
    for (const platform of ["facebook", "instagram", "linkedin"] as const) {
      for (const caption of (generated.social_posts[platform] || [])) {
        socialPosts.push({ business_id, platform, caption, status: "queued" });
      }
    }
    if (socialPosts.length) await supabase.from("social_posts").insert(socialPosts);

    await supabase.from("generation_jobs")
      .update({ status: "completed", completed_at: new Date().toISOString() })
      .eq("business_id", business_id);

    return NextResponse.json({
      success: true,
      stitch_project_id: projectId,
      template_options: templateOptions,
      generated,
    });

  } catch (error: any) {
    console.error("[generate] Error:", error);
    await supabase.from("generation_jobs")
      .update({ status: "failed", error: error.message })
      .eq("business_id", business_id).eq("status", "running");
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
