import { createAdminClient } from "@/lib/supabase-server";
import { NextResponse } from "next/server";

const GH_TOKEN = process.env.GITHUB_TOKEN!;
const VERCEL_TOKEN = process.env.VERCEL_TOKEN!;
const GH_ORG = process.env.GITHUB_ORG || "Amplify1-acct";

// ─── GitHub helpers ────────────────────────────────────────────────────────

async function ghFetch(path: string, method = "GET", body?: object) {
  const res = await fetch(`https://api.github.com${path}`, {
    method,
    headers: {
      Authorization: `token ${GH_TOKEN}`,
      Accept: "application/vnd.github+json",
      "Content-Type": "application/json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`GitHub ${method} ${path} → ${res.status}: ${err}`);
  }
  return res.json();
}

async function createRepo(repoName: string) {
  try {
    // Try to delete if exists (clean slate)
    await ghFetch(`/repos/${GH_ORG}/${repoName}`, "DELETE");
    await new Promise((r) => setTimeout(r, 2000));
  } catch {}

  return ghFetch(`/orgs/${GH_ORG}/repos`, "POST", {
    name: repoName,
    private: false,
    auto_init: false,
    description: "Generated by Exsisto",
  });
}

async function pushFiles(
  repoName: string,
  files: Record<string, string>
) {
  // Create blob for each file
  const blobs = await Promise.all(
    Object.entries(files).map(async ([path, content]) => {
      const blob = await ghFetch(`/repos/${GH_ORG}/${repoName}/git/blobs`, "POST", {
        content: Buffer.from(content).toString("base64"),
        encoding: "base64",
      });
      return { path, sha: blob.sha };
    })
  );

  // Create tree
  const tree = await ghFetch(`/repos/${GH_ORG}/${repoName}/git/trees`, "POST", {
    tree: blobs.map(({ path, sha }) => ({
      path,
      mode: "100644",
      type: "blob",
      sha,
    })),
  });

  // Create commit
  const commit = await ghFetch(`/repos/${GH_ORG}/${repoName}/git/commits`, "POST", {
    message: "Initial site generated by Exsisto",
    tree: tree.sha,
    parents: [],
  });

  // Create main branch
  await ghFetch(`/repos/${GH_ORG}/${repoName}/git/refs`, "POST", {
    ref: "refs/heads/main",
    sha: commit.sha,
  });

  return commit.sha;
}

// ─── Vercel helpers ────────────────────────────────────────────────────────

async function vercelFetch(path: string, method = "GET", body?: object) {
  const res = await fetch(`https://api.vercel.com${path}`, {
    method,
    headers: {
      Authorization: `Bearer ${VERCEL_TOKEN}`,
      "Content-Type": "application/json",
    },
    body: body ? JSON.stringify(body) : undefined,
  });
  if (!res.ok) {
    const err = await res.text();
    throw new Error(`Vercel ${method} ${path} → ${res.status}: ${err}`);
  }
  return res.json();
}

async function deployToVercel(repoName: string, projectName: string) {
  // Create Vercel project linked to GitHub repo
  let project;
  try {
    project = await vercelFetch("/v9/projects", "POST", {
      name: projectName,
      gitRepository: {
        type: "github",
        repo: `${GH_ORG}/${repoName}`,
      },
      framework: null, // static site
    });
  } catch (e: any) {
    // Project may already exist — fetch it
    const list = await vercelFetch(`/v9/projects/${projectName}`);
    project = list;
  }

  // Trigger a deployment
  const deployment = await vercelFetch("/v13/deployments", "POST", {
    name: projectName,
    gitSource: {
      type: "github",
      org: GH_ORG,
      repo: repoName,
      ref: "main",
    },
    projectSettings: {
      framework: null,
      outputDirectory: ".",
    },
  });

  return {
    deploymentId: deployment.id,
    url: `https://${deployment.url}`,
    projectId: project.id,
  };
}

async function waitForDeployment(deploymentId: string, maxWaitMs = 120000): Promise<string> {
  const start = Date.now();
  while (Date.now() - start < maxWaitMs) {
    await new Promise((r) => setTimeout(r, 5000));
    const dep = await vercelFetch(`/v13/deployments/${deploymentId}`);
    if (dep.readyState === "READY") {
      return `https://${dep.url}`;
    }
    if (dep.readyState === "ERROR" || dep.readyState === "CANCELED") {
      throw new Error(`Deployment ${dep.readyState}`);
    }
  }
  throw new Error("Deployment timed out");
}

// ─── Site HTML generator ───────────────────────────────────────────────────

function buildSiteHTML(business: any, website: any): string {
  const accentColor = business.accent_color || "#2563eb";
  const services = (website.services || []) as Array<{ name: string; description: string; icon: string }>;
  const stats = (website.stats || []) as Array<{ value: string; label: string }>;
  const testimonials = (website.testimonials || []) as Array<{ name: string; text: string; rating: number; location: string }>;
  const heroImage = website.hero_image_url || "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1400&h=700&fit=crop&auto=format";
  const tagline = business.tagline || `Professional ${business.industry || "services"} for your needs`;

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${website.meta_title || business.name}</title>
  <meta name="description" content="${website.meta_description || business.description}" />
  ${website.keywords ? `<meta name="keywords" content="${(website.keywords as string[]).join(", ")}" />` : ""}
  ${website.schema_markup ? `<script type="application/ld+json">${JSON.stringify(website.schema_markup)}</script>` : ""}
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=Playfair+Display:wght@700&display=swap" rel="stylesheet" />
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    :root {
      --accent: ${accentColor};
      --accent-light: ${accentColor}18;
      --black: #0a0a0a;
      --text: #1a1a1a;
      --text-mid: #555;
      --text-light: #888;
      --bg: #fff;
      --bg-soft: #f8f9fa;
      --border: #e8e8e8;
      --radius: 12px;
      --radius-sm: 8px;
    }
    html { scroll-behavior: smooth; }
    body { font-family: 'Inter', sans-serif; color: var(--text); background: var(--bg); line-height: 1.6; }
    a { color: inherit; text-decoration: none; }
    img { max-width: 100%; display: block; }

    /* NAV */
    nav {
      position: sticky; top: 0; z-index: 100;
      background: rgba(255,255,255,0.95); backdrop-filter: blur(12px);
      border-bottom: 1px solid var(--border);
      padding: 0 2rem; height: 64px;
      display: flex; align-items: center; justify-content: space-between;
    }
    .nav-logo { font-weight: 800; font-size: 1.25rem; color: var(--black); }
    .nav-logo span { color: var(--accent); }
    .nav-links { display: flex; gap: 2rem; align-items: center; }
    .nav-links a { font-size: 0.9rem; font-weight: 500; color: var(--text-mid); transition: color 0.2s; }
    .nav-links a:hover { color: var(--accent); }
    .nav-cta {
      background: var(--accent); color: white !important;
      padding: 0.5rem 1.25rem; border-radius: var(--radius-sm);
      font-weight: 600 !important;
    }
    .nav-cta:hover { opacity: 0.9; }

    /* HERO */
    .hero {
      position: relative; min-height: 620px;
      display: flex; align-items: center;
      background: linear-gradient(135deg, var(--black) 0%, #1a1a2e 100%);
      overflow: hidden;
    }
    .hero-bg {
      position: absolute; inset: 0;
      background-image: url('${heroImage}');
      background-size: cover; background-position: center;
      opacity: 0.2;
    }
    .hero-content {
      position: relative; z-index: 1;
      max-width: 1100px; margin: 0 auto; padding: 6rem 2rem;
    }
    .hero-badge {
      display: inline-flex; align-items: center; gap: 0.5rem;
      background: var(--accent-light); border: 1px solid var(--accent);
      color: var(--accent); padding: 0.35rem 1rem; border-radius: 999px;
      font-size: 0.8rem; font-weight: 600; margin-bottom: 1.5rem;
    }
    .hero h1 {
      font-family: 'Playfair Display', serif;
      font-size: clamp(2.5rem, 5vw, 4rem);
      color: white; line-height: 1.15; margin-bottom: 1.25rem;
    }
    .hero h1 em { color: var(--accent); font-style: normal; }
    .hero-sub { font-size: 1.2rem; color: rgba(255,255,255,0.75); max-width: 580px; margin-bottom: 2.5rem; }
    .hero-actions { display: flex; gap: 1rem; flex-wrap: wrap; }
    .btn {
      display: inline-flex; align-items: center; gap: 0.5rem;
      padding: 0.85rem 1.75rem; border-radius: var(--radius-sm);
      font-weight: 700; font-size: 0.95rem; transition: all 0.2s; cursor: pointer;
    }
    .btn-primary { background: var(--accent); color: white; }
    .btn-primary:hover { opacity: 0.9; transform: translateY(-1px); }
    .btn-outline { border: 2px solid rgba(255,255,255,0.3); color: white; }
    .btn-outline:hover { border-color: white; }
    .hero-stats {
      display: flex; gap: 3rem; margin-top: 4rem;
      flex-wrap: wrap;
    }
    .hero-stat-value { font-size: 2rem; font-weight: 800; color: white; }
    .hero-stat-label { font-size: 0.85rem; color: rgba(255,255,255,0.5); font-weight: 500; }

    /* SECTION */
    section { padding: 5rem 2rem; }
    .container { max-width: 1100px; margin: 0 auto; }
    .section-label {
      display: inline-block; color: var(--accent); font-weight: 700;
      font-size: 0.8rem; letter-spacing: 0.1em; text-transform: uppercase;
      margin-bottom: 0.75rem;
    }
    .section-title {
      font-family: 'Playfair Display', serif;
      font-size: clamp(1.8rem, 3vw, 2.5rem);
      color: var(--black); line-height: 1.25; margin-bottom: 1rem;
    }
    .section-sub { font-size: 1.05rem; color: var(--text-mid); max-width: 560px; }

    /* SERVICES */
    .services { background: var(--bg-soft); }
    .services-grid {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
      gap: 1.5rem; margin-top: 3rem;
    }
    .service-card {
      background: white; border: 1px solid var(--border);
      border-radius: var(--radius); padding: 2rem;
      transition: box-shadow 0.2s, transform 0.2s;
    }
    .service-card:hover { box-shadow: 0 8px 30px rgba(0,0,0,0.08); transform: translateY(-2px); }
    .service-icon { font-size: 2.5rem; margin-bottom: 1rem; }
    .service-name { font-weight: 700; font-size: 1.1rem; color: var(--black); margin-bottom: 0.5rem; }
    .service-desc { font-size: 0.9rem; color: var(--text-mid); line-height: 1.6; }

    /* STATS */
    .stats-band {
      background: var(--accent); padding: 3.5rem 2rem;
    }
    .stats-grid {
      max-width: 1100px; margin: 0 auto;
      display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
      gap: 2rem; text-align: center;
    }
    .stat-value { font-size: 2.5rem; font-weight: 800; color: white; }
    .stat-label { font-size: 0.9rem; color: rgba(255,255,255,0.7); font-weight: 500; margin-top: 0.25rem; }

    /* TESTIMONIALS */
    .testimonials-grid {
      display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
      gap: 1.5rem; margin-top: 3rem;
    }
    .testimonial-card {
      background: var(--bg-soft); border: 1px solid var(--border);
      border-radius: var(--radius); padding: 1.75rem;
    }
    .stars { color: var(--accent); font-size: 1rem; margin-bottom: 0.75rem; }
    .testimonial-text { font-size: 0.95rem; color: var(--text); line-height: 1.7; margin-bottom: 1rem; font-style: italic; }
    .testimonial-author { font-weight: 700; font-size: 0.9rem; color: var(--black); }
    .testimonial-location { font-size: 0.8rem; color: var(--text-light); }

    /* ABOUT */
    .about { background: var(--bg-soft); }
    .about-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 4rem; align-items: center; margin-top: 2rem; }
    .about-img { border-radius: var(--radius); overflow: hidden; aspect-ratio: 4/3; }
    .about-img img { width: 100%; height: 100%; object-fit: cover; }
    .about-text p { color: var(--text-mid); line-height: 1.8; margin-bottom: 1rem; }
    .about-text .btn { margin-top: 1rem; background: var(--accent); color: white; border: none; }

    /* CONTACT */
    .contact-wrapper {
      display: grid; grid-template-columns: 1fr 1fr; gap: 4rem;
      align-items: start; margin-top: 3rem;
    }
    .contact-info h3 { font-size: 1.2rem; font-weight: 700; margin-bottom: 1rem; }
    .contact-detail { display: flex; gap: 0.75rem; margin-bottom: 1rem; }
    .contact-detail-icon { font-size: 1.2rem; }
    .contact-detail-text { font-size: 0.95rem; color: var(--text-mid); }
    .contact-form-wrap { background: var(--bg-soft); border-radius: var(--radius); padding: 2rem; }
    .form-group { margin-bottom: 1.25rem; }
    .form-group label { display: block; font-weight: 600; font-size: 0.875rem; margin-bottom: 0.4rem; }
    .form-group input, .form-group textarea {
      width: 100%; padding: 0.75rem 1rem; border: 1px solid var(--border);
      border-radius: var(--radius-sm); font-family: inherit; font-size: 0.95rem;
      background: white; transition: border-color 0.2s;
    }
    .form-group input:focus, .form-group textarea:focus {
      outline: none; border-color: var(--accent);
    }
    .form-group textarea { min-height: 120px; resize: vertical; }
    .form-submit {
      width: 100%; padding: 0.85rem; background: var(--accent); color: white;
      border: none; border-radius: var(--radius-sm); font-weight: 700;
      font-size: 1rem; cursor: pointer; transition: opacity 0.2s;
    }
    .form-submit:hover { opacity: 0.9; }

    /* FOOTER */
    footer {
      background: var(--black); color: rgba(255,255,255,0.6);
      padding: 3rem 2rem; text-align: center;
    }
    .footer-logo { font-size: 1.5rem; font-weight: 800; color: white; margin-bottom: 0.5rem; }
    .footer-logo span { color: var(--accent); }
    .footer-tagline { margin-bottom: 2rem; font-size: 0.9rem; }
    .footer-links { display: flex; gap: 2rem; justify-content: center; flex-wrap: wrap; margin-bottom: 2rem; }
    .footer-links a { color: rgba(255,255,255,0.5); font-size: 0.875rem; transition: color 0.2s; }
    .footer-links a:hover { color: white; }
    .footer-copy { font-size: 0.8rem; color: rgba(255,255,255,0.3); }

    /* RESPONSIVE */
    @media (max-width: 768px) {
      .nav-links { display: none; }
      .about-grid, .contact-wrapper { grid-template-columns: 1fr; }
      .hero-stats { gap: 2rem; }
    }
  </style>
</head>
<body>

<nav>
  <div class="nav-logo">${business.emoji || "🏆"} <span>${business.name}</span></div>
  <div class="nav-links">
    <a href="#services">Services</a>
    <a href="#about">About</a>
    <a href="#testimonials">Reviews</a>
    <a href="#contact" class="nav-cta">Get in touch</a>
  </div>
</nav>

<div class="hero">
  <div class="hero-bg"></div>
  <div class="hero-content">
    <div class="hero-badge">✦ ${business.industry || "Professional Services"}</div>
    <h1>${business.name}<br/><em>${tagline}</em></h1>
    <p class="hero-sub">${business.description}</p>
    <div class="hero-actions">
      <a href="#contact" class="btn btn-primary">Get a free consultation →</a>
      <a href="#services" class="btn btn-outline">Our services</a>
    </div>
    ${stats.length > 0 ? `
    <div class="hero-stats">
      ${stats.slice(0, 4).map(s => `
      <div>
        <div class="hero-stat-value">${s.value}</div>
        <div class="hero-stat-label">${s.label}</div>
      </div>`).join("")}
    </div>` : ""}
  </div>
</div>

<section id="services" class="services">
  <div class="container">
    <span class="section-label">What we offer</span>
    <h2 class="section-title">Our services</h2>
    <p class="section-sub">Everything you need, delivered with expertise and care.</p>
    <div class="services-grid">
      ${services.map(s => `
      <div class="service-card">
        <div class="service-icon">${s.icon}</div>
        <div class="service-name">${s.name}</div>
        <div class="service-desc">${s.description}</div>
      </div>`).join("")}
    </div>
  </div>
</section>

${stats.length > 0 ? `
<div class="stats-band">
  <div class="stats-grid">
    ${stats.map(s => `
    <div>
      <div class="stat-value">${s.value}</div>
      <div class="stat-label">${s.label}</div>
    </div>`).join("")}
  </div>
</div>` : ""}

<section id="about" class="about">
  <div class="container">
    <div class="about-grid">
      <div class="about-img">
        <img src="${heroImage}" alt="${business.name}" loading="lazy" />
      </div>
      <div class="about-text">
        <span class="section-label">About us</span>
        <h2 class="section-title">Who we are</h2>
        <p>${business.description}</p>
        <p>We're committed to delivering exceptional results for every client. Our team brings deep expertise and a personal touch to everything we do.</p>
        ${business.city ? `<p>Proudly serving ${business.city}${business.state ? `, ${business.state}` : ""} and surrounding areas.</p>` : ""}
        <a href="#contact" class="btn">Get in touch →</a>
      </div>
    </div>
  </div>
</section>

${testimonials.length > 0 ? `
<section id="testimonials">
  <div class="container">
    <span class="section-label">What clients say</span>
    <h2 class="section-title">Reviews</h2>
    <p class="section-sub">Real stories from real customers.</p>
    <div class="testimonials-grid">
      ${testimonials.map(t => `
      <div class="testimonial-card">
        <div class="stars">${"★".repeat(t.rating || 5)}</div>
        <div class="testimonial-text">"${t.text}"</div>
        <div class="testimonial-author">${t.name}</div>
        <div class="testimonial-location">${t.location || ""}</div>
      </div>`).join("")}
    </div>
  </div>
</section>` : ""}

<section id="contact">
  <div class="container">
    <span class="section-label">Get in touch</span>
    <h2 class="section-title">Contact us</h2>
    <div class="contact-wrapper">
      <div class="contact-info">
        <h3>We'd love to hear from you</h3>
        <p style="color: var(--text-mid); margin-bottom: 2rem; line-height: 1.7;">
          Whether you have a question, want a quote, or just want to say hello — we're here and ready to help.
        </p>
        ${business.phone ? `<div class="contact-detail"><div class="contact-detail-icon">📞</div><div class="contact-detail-text">${business.phone}</div></div>` : ""}
        ${business.email ? `<div class="contact-detail"><div class="contact-detail-icon">✉️</div><div class="contact-detail-text">${business.email}</div></div>` : ""}
        ${business.address ? `<div class="contact-detail"><div class="contact-detail-icon">📍</div><div class="contact-detail-text">${business.address}${business.city ? `, ${business.city}` : ""}${business.state ? `, ${business.state}` : ""}</div></div>` : ""}
        ${business.city && !business.address ? `<div class="contact-detail"><div class="contact-detail-icon">📍</div><div class="contact-detail-text">${business.city}${business.state ? `, ${business.state}` : ""}</div></div>` : ""}
      </div>
      <div class="contact-form-wrap">
        <form onsubmit="handleSubmit(event)">
          <div class="form-group">
            <label>Your name</label>
            <input type="text" placeholder="Jane Smith" required />
          </div>
          <div class="form-group">
            <label>Email address</label>
            <input type="email" placeholder="jane@example.com" required />
          </div>
          <div class="form-group">
            <label>Message</label>
            <textarea placeholder="How can we help you?"></textarea>
          </div>
          <button type="submit" class="form-submit">Send message →</button>
        </form>
      </div>
    </div>
  </div>
</section>

<footer>
  <div class="footer-logo">${business.emoji || "🏆"} <span>${business.name}</span></div>
  <div class="footer-tagline">${tagline}</div>
  <div class="footer-links">
    <a href="#services">Services</a>
    <a href="#about">About</a>
    <a href="#testimonials">Reviews</a>
    <a href="#contact">Contact</a>
  </div>
  <div class="footer-copy">© ${new Date().getFullYear()} ${business.name}. All rights reserved. Website by <a href="https://exsisto.ai" style="color:rgba(255,255,255,0.4)">Exsisto</a>.</div>
</footer>

<script>
function handleSubmit(e) {
  e.preventDefault();
  const btn = e.target.querySelector('.form-submit');
  btn.textContent = '✓ Message sent!';
  btn.style.background = '#16a34a';
  setTimeout(() => { btn.textContent = 'Send message →'; btn.style.background = ''; }, 3000);
  e.target.reset();
}
</script>

</body>
</html>`;
}

// ─── Main handler ──────────────────────────────────────────────────────────

export async function POST(request: Request) {
  const body = await request.json();
  const { business_id } = body;
  if (!business_id) {
    return NextResponse.json({ error: "business_id required" }, { status: 400 });
  }

  if (!GH_TOKEN || !VERCEL_TOKEN) {
    return NextResponse.json({ error: "GITHUB_TOKEN and VERCEL_TOKEN env vars required" }, { status: 500 });
  }

  const supabase = createAdminClient();

  // Fetch business + website data
  const { data: business, error: bizErr } = await supabase
    .from("businesses")
    .select("*")
    .eq("id", business_id)
    .single();

  if (bizErr || !business) {
    return NextResponse.json({ error: "Business not found" }, { status: 404 });
  }

  const { data: website } = await supabase
    .from("websites")
    .select("*")
    .eq("business_id", business_id)
    .single();

  // Update status to generating
  await supabase
    .from("websites")
    .update({ status: "generating" })
    .eq("business_id", business_id);

  try {
    // Build slug for repo/project names
    const slug = business.name
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 40);

    const repoName = `exsisto-site-${slug}`;
    const projectName = `exsisto-${slug}`;

    // Fetch HTML from chosen Stitch screen if provided
    let html = "";
    const screenId = body.screen_id;
    const stitchProjectId = body.project_id || website?.stitch_project_id;
    if (screenId && stitchProjectId) {
      try {
        const codeRes = await fetch(
          `https://stitch.googleapis.com/v1alpha/projects/${stitchProjectId}/screens/${screenId}/code`,
          { headers: { Authorization: `Bearer ${process.env.STITCH_API_KEY}` } }
        );
        if (codeRes.ok) {
          const codeData = await codeRes.json();
          if (codeData.downloadUrl) {
            const r = await fetch(codeData.downloadUrl);
            html = await r.text();
          } else if (codeData.html) {
            html = codeData.html;
          }
        }
      } catch (e) { console.warn("Stitch fetch failed, using fallback:", e); }
    }
    if (!html) {
      html = (website?.custom_html as string) || buildSiteHTML(business, website || {});
    }

    // Push to GitHub
    await createRepo(repoName);
    await pushFiles(repoName, {
      "index.html": html,
    });

    // Deploy to Vercel
    const { deploymentId, url } = await deployToVercel(repoName, projectName);

    // Wait for deployment to be ready (up to 2 min)
    let liveUrl: string;
    try {
      liveUrl = await waitForDeployment(deploymentId);
    } catch {
      // Use the URL even if we timed out — it's usually ready
      liveUrl = url;
    }

    // Save live URL back to Supabase
    await supabase
      .from("websites")
      .update({
        status: "live",
        vercel_url: liveUrl,
        deployed_at: new Date().toISOString(),
      })
      .eq("business_id", business_id);

    await supabase
      .from("businesses")
      .update({ website_url: liveUrl })
      .eq("id", business_id);

    return NextResponse.json({ success: true, url: liveUrl, deploymentId });
  } catch (error: any) {
    await supabase
      .from("websites")
      .update({ status: "error" })
      .eq("business_id", business_id);

    console.error("Deploy error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
